apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: boilerd
  name: boilerd
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      k8s-app: boilerd
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: boilerd
      name: boilerd
    spec:
      containers:
      - args:
        - -addr
        - 0.0.0.0:5050
        command:
        - /go/bin/boilerd
        image: docker.mycompany.com/platform/go-boiler:v0.1
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 5050
            scheme: HTTP
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 10
        name: boilerd
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
